### PR TITLE
Add Grid to the postcss config for autoprefixer

### PR DESCRIPTION
**Pull request by nomad-mystic**
Cleaned out a couple .DS_stores, ticked up the version number, and added grid to the Autoprefixer config for PostCSS to pick up.

### CODE REVIEW

**Comment by codyrobert** [comment]
@nomad-mystic i'm not familiar with that config option, what does it do?

**Comment by nomad-mystic** [comment]
@codyrobert 

It adds -ms- prefixes to grid properties and changes the properties to match something IE understands. 

grid-template-columns = -ms-grid-columns
grid-column = -ms-grid-column

I found that you have to explicitly say you want to have Autoprefixer prefix grid. I found the option here: https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/

Keith

**Comment by codyrobert** [comment]
awesome - sounds good

**Review by codyrobert — APPROVED** [review]

**Review by chrislarrycarl — APPROVED** [review]
Thanks for the extra details @nomad-mystic, it helps provide context for the review and will serve as good reference if/when we need to refer back to this.

We will also want to get this change added to our 2.0 branch so we can ensure parity for future builds.

**Pull request merged**
